cache:
  directories:
    - $HOME/.iv2
    - $HOME/.sbt
deploy:
  api_key:
    secure: "cMeZPmm8+jRvhQI/mQ5TNVDCGgKHuaVBf/jIMmqb9ybV3E9oqfr6c7BHbJ2+nWV4y5acTS4pQHxNhsOWxROPCOpLpFd2HIZl9sSvWKVoBMFLVSkHyRhmr6c3leUgk2EIzXp2VXn6bhhq0B03Sp6cYTeqKElZTTUwDf5fmDG6PVGQ8N9JnSEJHC3l3hGgIP/ljxORL/9sA7mtzo8t3rpL6cPkRfGTvN7J/47l9RNojNRQ0/uBS6vUZJGTNE1hDw1lfOICHITsVT6oeevYDwZxEuEeF+Lfl5V2F7mUX0khNNqE5LoF5D0KLDnFK+el4UUu/jdR/NCMkT8EruSh/6q7r9xvPQTwZBO6q2B+9FjnUOMXm7A07L9MM08BYYqZPCfd3tJHfd1TWnSzdjG+47TFI0dlCZI6OSvC23fSJ2j6lUTX1/TxHyF3vqlj7f8gx5q2SeVMfc3EGHzJ1Bf49RVRZwUzmXZlUFJUnZxHnvZxTV8V8tHdikaQStdJJAEESuPIVcyXlAbmdzhS0VE4fQNX+3gxE3nxH5K9mShtEzBIbTw2KsH1xscaJfx8WWK7DDumW/CAUQUEmbu8xJP6zV5CvTbINRZMjiHihL7Z/GRB2VIctf+pRV8EPtBdUgA70lDTznLHjBQJhvfhZ6MpTKRRbnflf7WQ6ZB0iS88Dms9pEo="
  file: '*/target/**/*.jar'
  file_glob: true
  on:
    tags: true
  provider: releases
  skip_cleanup: true
git:
  depth: 1
jdk:
  - openjdk8
dist: bionic
language: scala
script:
  - '[ "$TRAVIS_PULL_REQUEST" != false ] || export SBT_OPTS=-Dbuild.version=${TRAVIS_TAG:-$TRAVIS_BRANCH-SNAPSHOT}'
  - sbt 'all compile test'
  - |
    if [ "$TRAVIS_SECURE_ENV_VARS" == true ]; then
      echo "$PGP_SECRET" | base64 --decode | gpg --import
      if [ -z "$TRAVIS_TAG" ]; then
          sbt publishSigned
      else
          sbt "sonatypeOpen sbt-android-room-$TRAVIS_TAG" publishSigned sonatypeReleaseAll
      fi
    fi
